### ISSUE TITLE
ClassGenerator: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by alex-sainer** [zendframework/zend-code#81] opened 2016-06-30 13:08 UTC
Hi @veewee , 

there is an error within this fix: https://github.com/zendframework/zend-code/commit/4a6f4ab33480923ac6553ded903c97de168f37fe

if ClassNames with leading Backslash are used (i.E. \My\Base\Class), the returnvalue of the Method Zend\Code\Generator\ClassGenerator::generateShortOrCompleteClassname() will be \\My\Base\Class

as a quickfix i would suggest something like following: 

```php
private function generateShortOrCompleteClassname($fqnClassName)
    {
        $parts = explode('\\', $fqnClassName);
        $parts = array_filter($parts);
        $className = array_pop($parts);
        $classNamespace = implode('\\', $parts);
        $currentNamespace = (string) $this->getNamespaceName();

        if ($classNamespace === $currentNamespace || in_array($fqnClassName, $this->getUses())) {
            return $className;
        }

        return '\\' . $fqnClassName;
    }
```

see the "array_filter()" method after explode

**Comment by Ocramius** [comment] 2016-06-30 13:08
Duplicate of #75

**Closed by Ocramius** 2016-06-30 13:08 UTC
