### ISSUE TITLE
TokenArrayScanner fails on php 7.0.5

### ISSUE THREAD

**Issue by danez** [zendframework/zend-code#49] opened 2016-04-01 14:32 UTC
As with PHP 7.0.5 the TokenArrayScanner is not working anymore with zend-code 2.
I have no further info, except that when using the FileScanner it does not produce any info when calling scan().

**Comment by Ocramius** [comment] 2016-04-02 06:11
@danez was there a change from 7.0.4 to 7.0.5 that broke this, or is the change just related with PHP 7.x?

**Comment by danez** [comment] 2016-04-02 09:06
It was working with 7.0.4, but with 7.0.5 it does not. Not sure which change in php could have caused that. There is one where they mention variable scope, which could be. But I also couldn't really found the issue, debugging all the goto statements in the scanner is a little bit hard. When I tried debugging it seemed that inside ->scan() the $tokenType is never changing.

**Comment by Ocramius** [comment] 2016-04-02 09:16
@danez should be brought up with php internals then: there might be a BC break that wasn't documented in the release log.

**Comment by danez** [comment] 2016-04-02 13:34
I reported it: https://bugs.php.net/bug.php?id=71948

**Comment by bashofmann** [comment] 2016-04-04 08:09
The issue is apparently already fixed with https://bugs.php.net/bug.php?id=71914 and hopefully will be included in 7.0.6

**Closed** 2016-04-20 17:32 UTC
